apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpaca-prod
  template:
    metadata:
      labels:
        app: alpaca-prod
    spec:
      containers:
        - name: alpaca-prod
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            periodSeconds: 2
            initialDelaySeconds: 0
            failureThreshold: 3
            successThreshold: 1
          image: gcr.io/kuar-demo/kuard-amd64:blue
          ports:
            - containerPort: 8080
